name: Artifact Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact from specific folder
        uses: actions/upload-artifact@v4
        with:
          name: t1-artifact-${{ github.run_id }}
          path: t1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact to custom folder
        uses: actions/download-artifact@v4
        with:
          name: t1-artifact-${{ github.run_id }}
          path: ./t1

      - name: List downloaded files
        run: |
          echo "Listing downloaded contents:"
          ls -R ./t1

      - name: CD into downloaded folder and show contents
        run: |
          cd t1
          echo "Current directory: $(pwd)"
          echo "Files:"
          ls
