name: Call Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'World'

jobs:
  greet:
    uses: ./.github/workflows/reusable-helloworld.yaml
