name: Call Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Pre-step before calling reusable workflow
        env:
          v1: ${{ inputs.name == 'prod' && 'snowflake-prod' || 'snowflake-dev' }}
          
        run: |
            echo "Preparing environment : ${{ env.name }}"

      - name: Call reusable workflow
        uses: ./.github/workflows/reusable-helloworld.yaml

      - name: Post-step after calling reusable workflow
        run: echo "Reusable workflow completed"
