name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  hello_world_1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Say Hello from Job 1
        run: echo "Hello from Job 1 in dev environment!"
  
  approval_to_hello_world_2:
    runs-on: ubuntu-latest
    needs: [hello_world_1]
    environment: Approval-Env
    steps:
      - run: echo "Approved Successfully"
  
  hello_world_2:
    runs-on: ubuntu-latest
    needs: [approval_to_hello_world_2]
    environment: dev
    steps:
      - name: Say Hello from Job 2
        run: echo "Hello from Job 2 in dev environment!"
