name: Deploy with Key Vault Secrets

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Azure Login
      #   run: |
      #    az login

      - name: Fetch Secrets from Key Vault
        uses: ./.github/actions/fetch-keyvault-secrets
        with:
          keyvault-name: 'hariv-kvv'
          secret-names: 'k1,k2'

      - name: Use Retrieved Secrets
        run: |
          echo "Secret1-: $Secret1"
          echo "Secret2: $Secret2"
