name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: exit 0  # Simulating success

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Runs after job1
    steps:
      - name: Run Job 2
        run: exit 1  # Simulating failure

  job3:
    runs-on: ubuntu-latest
    needs: job2  # Runs after job2
    steps:
      - name: Run Job 3
        run: exit 0  # This won't run if job2 fails

  notify:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]  # Add all jobs here
    if: failure()
    steps:
      - name: Send Notification
        run: echo "🚨 Pipeline failed in one of the jobs!"
