name: CI/CD Pipeline - Master Test

on:
  workflow_call:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Run Job 12
        run: |
            echo "printing Job1 ${{ vars.t1 }}"
