name: CI/CD Pipeline - Master Test

on:
  workflow_call:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: |
            echo "printing Job1"
