name: Reusable Hello World

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  hello_world:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Say Hello from Job 1
        run: echo "Hello from Job 1 in ${{ inputs.environment }} environment!"
