name: Secret Mask Example

on:
  push:
    branches:
      - master
jobs:
  set-masked-env-pwsh:
    runs-on: windows-latest
    steps:
      - name: Set and mask environment variable in PowerShell
        shell: pwsh
        run: |
          $secretValue = "super-secret-data"

          # Mask the value to prevent it from appearing in logs
          Write-Output "::add-mask::$secretValue"

          # Export the variable as a GitHub Actions env var
          "[MY_SECRET]=$secretValue" >> $env:GITHUB_ENV
          
      - name: Use the masked variable
        shell: pwsh
        run: |
          # This will use the masked variable
          if ($env:[MY_SECRET]) {
            Write-Output "Masked variable is set and being used."
          }
