name: Secret Mask Example

on:
  push:
    branches:
      - master
jobs:
  masked-env-pwsh:
    runs-on: windows-latest
    steps:
      - name: Set and mask env variable in PowerShell
        shell: pwsh
        run: |
          $secretValue = "super-secret-data"

          # Mask the value so it doesn't appear in logs
          Write-Output "::add-mask::$secretValue"

          # Set as env var for later steps
          "[MY_SECRET]=$secretValue" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Use the masked variable in PowerShell
        shell: pwsh
        run: |
          if ($env:MY_SECRET) {
            Write-Output "Masked variable is set and being used."
          } else {
            Write-Output "Masked variable is NOT set."
          }

