name: Secret Mask Example

on:
  push:
    branches:
      - master

jobs:
  test-masked:
    runs-on: windows-latest
    steps:
      - name: Set and mask secret variable
        shell: pwsh
        run: |
          $secret = "super-secret-data"
          Write-Output "::add-mask::$secret"
          Add-Content -Path $env:GITHUB_ENV -Value "MY_SECRET=$secret"

      - name: Access the masked variable
        shell: pwsh
        run: |
          if ($env:MY_SECRET) {
            Write-Output "✅ Masked variable is set and being used."
          } else {
            Write-Output "❌ Masked variable is NOT set."
          }

      - name: Show redacted value
        shell: pwsh
        run: |
          Write-Output "MY_SECRET = $env:MY_SECRET"

